### ISSUE TITLE
Cannot open image on wsl

### ISSUE THREAD

**Issue by t1gu1** [mapeditor/tiled#2773]
When the image is in wsl2, it wont open it.

e.g. : `\\wsl$\Ubuntu-18.04\assets\textures\cavesofgallet_tiles.png`

But it write `/Ubuntu-18.04/assets/textures/cavesofgallet_tiles.png` without the `\\wsl$`.

Any other program can open the image.

![image](https://user-images.githubusercontent.com/12479055/77050698-8711dc80-69a0-11ea-8332-93e9622b0c63.png)

---

I move the image outside wsl folder and it works.

---

**What is wsl2?**
Wsl is: windows Subsystem Linux.
And it run linux on window in a more native way than a VM does.
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

**Comment by danman113** [comment]
I second this one. It would be great to keep all of my files in source control.

**Comment by rallu** [comment]
Another thumbs up. Currently I have to use copy scripts between WSL and Windows to get Tiled reading files.

**Comment by bjorn** [comment]
Alright, I have WSL2 installed now. On first test, it appears that it might be a problem in Qt because the URL given in a drop event for example simply has the WSL2 native path, which does not make the file accessible through the Windows file API.

![image](https://user-images.githubusercontent.com/531764/95969674-51868200-0e0f-11eb-8c7a-0936118692c1.png)

I found [QTBUG-86321](https://bugreports.qt.io/browse/QTBUG-86321) already open about this issue, and unfortunately unresolved.

But I get the same problem when trying to open any file under `\\wsl$` using the file dialog, also in Qt Creator:

![image](https://user-images.githubusercontent.com/531764/95969904-99a5a480-0e0f-11eb-8223-ada1fe1c3613.png)

Even is not providing me with the URLs necessary to open such files:

![image](https://user-images.githubusercontent.com/531764/95971423-81368980-0e11-11eb-823a-be41d056cb95.png)


I guess the only solution I could suggest right now, would be to store your project files on the Windows file system, and if you really need to use them from WSL2, that you access them through `/mnt/c` for example.

Alternatively, if this is about using git in WSL2, why not use Git for Windows instead?

**Comment by rallu** [comment]
In reality, WSL2 is the only option when developing web apps on Windows. Everything else is just so much more inferior compared.  Using only `/mnt/c` isn't really option due to performance and missing file permissions.

So I'm now using two folders for now. One in `/home` where I develop and one in `/mnt/c` where I edit tiled files and sync these folders through git origin.

So let's hope that Qt fixes this bug sometime in the future.

**Comment by mccxiv** [comment]
Comment claims the Qt bug is fixed in 5.15.2? 👀 https://bugreports.qt.io/browse/QTBUG-86321?focusedCommentId=537686&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-537686

**Comment by bjorn** [comment]
@mccxiv Then this problem might have been fixed (or partly fixed) in the Tiled snapshots since 2020-11-24, which is when they were updated to build against Qt 5.15.2. I guess it's time to look into this issue again then since there are likely still some changes needed on the Tiled side as well.

**Comment by danman113** [comment]
Initial investigation leans towards partially fixed. Creating a new Tilemap/set seems to work just fine, but when I try to re-open the tileset it saves the linux path rather than the WSL path, so all of the image references are broken.

[Here's a screenshot of the error I get when importing](https://imgur.com/AUqabFE)

**Comment by auberryberry** [comment]
+1 just fallen foul of this myself, a true workflow killer, @bjorn would some beer money help? :)

**Comment by bjorn** [comment]
@auberryberry Well, all Tiled development is funded by beer money (or coffee money, as I'd prefer to call it). :-) I appreciate any contribution, though I'll make sure to look into this soon either way.

**Comment by auberryberry** [comment]
Where does one hook you up with a coffee ☕️ Fund?

________________________________

**Comment by bjorn** [comment]
@auberryberry Usually the most effective way (0% lost to fees) is [GitHub Sponsors](https://github.com/sponsors/bjorn). If recurring is not your thing, I'd recommend either [buying Tiled on itch.io](https://thorbjorn.itch.io/) or [Liberapay](https://liberapay.com/Tiled/). Thanks!

**Comment by auberryberry** [comment]
@bjorn $50 on itch 💎💎🤲 done!

**Comment by bjorn** [comment]
Thanks a lot for your generous donation, @auberryberry!

I've just finished setting up WSL2 with Ubuntu 20.04 and then ran latest `master` compiled against Qt 5.15.2. However, so far I've not been able to reproduce this issue anymore.

Specifically, I tried:

* Checking out the Tiled repository to my home directory in Ubuntu 20.04 and opening a few of the examples. It could open them without issues.
* Creating a new image collection tileset, saving into the WSL folder, adding images from the WSL folder (either by "Add Tiles" or Drag & Drop). It correctly saved relative file references. Restarting Tiled and reopening the files worked fine.
* Changing the existing image of a tileset through file chooser.
* Creating an image layer and picking an image within the WSL path. Also tried to pick an update outside the WSL path, then the file reference was saved as absolute (not desirable, but it worked).
* To make sure, I've also tested a bit with the latest snapshot available on itch.io (2021.02.15) rather than the local-compiled version, but I couldn't reproduce any issues there either.

@danman113, @auberryberry If you can reproduce this, can you provide a bit more information so that we can narrow it down?

**Comment by danman113** [comment]
Whoops, turns out when I re-opened the file, I was using the older version of tiled. Manually opening the file works fine, so it gets a 👍 from me.

Sorry for the confusion!

**Comment by bjorn** [comment]
@danman113 Ok, that's a relief! It was good to give this a proper round of testing anyway, so now we can confidently close this issue. Fix available in latest snapshot and the soon-to-be-released Tiled 1.5! :-)
