### ISSUE TITLE
TileMap.tilesets.some sometimes returns a null element

### ISSUE THREAD

**Issue by Miepee** [mapeditor/tiled#3292]
**Describe the bug**
The following line in a JS extension fails *sometimes* with the error message `Cannot read property 'name' of null`.:
`if (map.tilesets.some(item => item.name == tileset.name))`

**To Reproduce**
Here is an example map and an example extension that triggers the bug:
[bugMaterial.zip](https://github.com/mapeditor/tiled/files/8190985/bugMaterial.zip)
- put the extension js file into the extension folder, and replace the file path in line 7 to any image you want to
- open the json2 room via Tiled
- notice how sometimes Tiled spews out an error while at other times it will load the map

**Expected behavior**
The tileset collection should only have valid tilesets, it should not return a null item at all.

**Platform (please complete the following information):**
 - OS: Windows 10, Arch Linux via WSL2
 - Version: Tiled 1.8.2

**Comment by bjorn** [comment]
Hmm, this script appears to even cause a familiar assertion error:

![image](https://user-images.githubusercontent.com/531764/157001173-92d8a8de-c391-4e52-8ca3-7c7462485e79.png)

I had pushed 09b37e750ad7a9aa1aee72e54b2498e82ea0f01a as a workaround for one way this assertion could be triggered, but as I noted in https://github.com/mapeditor/tiled/issues/3229#issuecomment-1018403142, I'm not entirely sure this assertion is correct. Of course, now I also wonder whether this has something to do with the `null` values.

**Comment by bjorn** [comment]
Btw, apart from the problem with `null` values, there are a few things to note about this script, which would make it a lot more efficient:

* You only need one `tilesLayer.edit()` call and one `editTile.apply()` call, outside of the loop over `data.tiles`, since all edits are made to the same layer.
* Rather than creating each tileset, then looking whether it exists, and then filtering again to obtain it, you could initialize first and then check if you need to create a new tileset:
```js
let tileset = tileset = map.tilesets.filter(item => item.name == tileObj.background_definition)[0];
if (!tileset) {
    tileset = new Tileset(tileObj.background_definition);
    tileset.setTileSize(16, 16);
    tileset.image = tilesetImage;
    map.addTileset(tileset);
}
```
* Even better would be to remember the created tilesets in a custom [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) instance so they can be quickly looked up by name.
* You need to set the tile size and width / height of the map for it to render correctly.

**Comment by bjorn** [comment]
I'll post the example with using a Map, since this also provides a workaround for the issue:

```js
        let createdTilesets = new Map()

        // Add tiles and their data
        for (i = data.tiles.length-1; i>=0; i--)
        {
            let tileObj = data.tiles[i];

            let tileset = createdTilesets.get(tileObj.background_definition);
            if (!tileset) {
                tileset = new Tileset(tileObj.background_definition);
                createdTilesets.set(tileObj.background_definition, tileset);
```

Not only is this a lot more efficient, but it also keeps references to the created tilesets in the script. This avoids those objects from being garbage collected, which is likely what is causing the `null` issue.

What happens when calling `map.tilesets`, is that each tileset used by the map is wrapped in an object owned by the script engine, which references the C++ tileset instance. In the interest of performance (and to be able to directly compare them in JS), I am caching these wrappers so that when accessing `map.tilesets` again, I can return the same wrapper objects.

However, since no reference to the wrapper objects is kept in the script, the garbage collector might decide to free them. I try to detect this on the C++ side by checking that its destructor hasn't been called yet and whether the reference to the wrapper object turns into a `null` value when creating a script value, but apparently this is still not a 100% reliable approach.

I think a possible fix might be to move ownership of the wrapper objects from JS to C++. There, the wrappers may stay alive longer than necessary, but it would avoid this garbage collection issue and likely be better for overall performance.

**Comment by Miepee** [comment]
Thanks for all the suggestions! Am not that familiar with JS, so these greatly help not only making it more efficient but also having it more readable.

**Comment by bjorn** [comment]
It seems the fix I pushed for #3290 (9bad4facf888fb4a2550644d777d8ff79150cbec) also mostly avoids this problem, though for some reason I still saw it occur once, but I couldn't reproduce it. Maybe you could download a build (or compile yourself from the 1.8 branch) and see if it is also resolved for you.

Now, I just noticed that I still broke the snap build since I had to use a private Qt header...

**Comment by Miepee** [comment]
Using the Tiled-win64 build from [here](https://github.com/mapeditor/tiled/actions/runs/1950688148), still happens regularly for me. Feels like it happens less now, but still often.

**Comment by bjorn** [comment]
@Miepee Oh well, thanks for testing! It's weird since it seems a wrapper object that is not already marked for delete might still be marked for deletion after its JS value has been set up. I'm afraid a definite fix for this issue might require some changes in the behavior of the API, which I'd explore for Tiled 1.9 then.

**Comment by eishiya** [comment]
Qt6 fixed some garbage collection issues that results in layer.objects, tileset.tiles, etc sometimes containing invalid entities. Perhaps this issue was also fixed by that?

**Comment by bjorn** [comment]
@eishiya I think it's a reasonable assumption.

@Miepee Please reopen when you still notice this with Tiled built against Qt 6 (the Tiled 1.10 release will be primarily built against Qt 6.4).
